### ISSUE TITLE
Wrong licence translation in the LICENCE file? :)

### ISSUE THREAD

**Issue by justinclift** [maicol07/school_life_diary_pc#2]
Just noticed a small weirdness, that I **think** is a bug.  Not sure, but it's probably worth mentioning. :smile:

With the licence file, the top section seems to be an unofficial translation for the GNU GPL version 3.  The bottom (english section), is the english version of a different licence, the GNU **Affero** GPL version 3:

* https://github.com/maicol07/school_life_diary_pc/blob/5ab4fb0f5adf15ef38118623acf90ca5df95ffa6/LICENSE#L3
* https://github.com/maicol07/school_life_diary_pc/blob/5ab4fb0f5adf15ef38118623acf90ca5df95ffa6/LICENSE#L141

The "Affero" GPL licence is a bit different to the non-Afferi GPL one.  I'm not sure which one you're wanting to use, but the Italian and English versions should probably be for the same one.

Hope that helps. :smile:

**Comment by maicol07** [comment]
Thanks. Actually there isn't an official Italian translation of this license, so I will make and check it with athe help of a translator.

**Comment by justinclift** [comment]
Cool. :smile:
